### ISSUE TITLE
Использование в assign массива переменных

### ISSUE THREAD

**Issue by maxisoft-git** [fenom-template/storage#1]
Очень нужна возможность передать в assign не только переменную но также ассоциациынй массив, чтобы не писать портянку из цепочки assign

**Comment by bzick** [comment]
Есть

``` php
$fenom->assignAll($vars);
```

второй флаг указывает мерджить с текущим значением или нет

**Comment by bzick** [comment]
В readme не было указано про этот метод, исправил
